### ISSUE TITLE
Links to social media at bottom of page

### ISSUE THREAD

**Issue by pierpressure** [jnaulty/footplusplus-website#2]
Need to add links as well as privacy policy to bottom of webpage

**Comment by lambdaloop** [comment]
what links do you wanna add?

**Comment by pierpressure** [comment]
https://www.instagram.com/footplusplus/

https://www.facebook.com/pg/FootPP/about/

we will need a twitter too probably but those two for now should be good

**Comment by PeggyWang0** [comment]
We have a Twitter and LinkedIn too

**Comment by PeggyWang0** [comment]
[https://twitter.com/footplusplus](https://twitter.com/footplusplus
)
Have to update LinkedIn https://www.linkedin.com/company/footplusplus

**Comment by PeggyWang0** [comment]
Uploaded social media icons to images, don't know how to add them/add a footer to the website itself
